"use client";

import { useState, useEffect } from "react";
import { useMutation, useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import { FileText, Loader2, Eye } from "lucide-react";
import { toast } from "sonner";

interface EmailTemplate {
  id: string;
  name: string;
  subject: string;
  body: string;
  variables: string[];
}

const defaultTemplates: EmailTemplate[] = [
  {
    id: "forgot_password",
    name: "Forgot Password",
    subject: "Reset Your Password - {company_name}",
    body: `Dear {user},

Somebody (hopefully you) requested a new password for the account for {email}
Your new password is {password}
Kindly update your password after login. We'll be here to help you with any step along the way

Note :- Do not reply to this notification message, this message was auto-generated by the sender's security system.

All Rights Reserved.`,
    variables: ["user", "email", "password", "company_name"],
  },
  {
    id: "booking_confirmation",
    name: "Booking Confirmation",
    subject: "Booking Confirmed - {service_name}",
    body: `Dear {customer_name},

Your booking has been confirmed!

Service: {service_name}
Date: {booking_date}
Time: {booking_time}
Vehicle: {vehicle_info}

Please arrive 10 minutes before your scheduled time.

Best regards,
{company_name}`,
    variables: ["customer_name", "service_name", "booking_date", "booking_time", "vehicle_info", "company_name"],
  },
  {
    id: "invoice",
    name: "Invoice",
    subject: "Invoice #{invoice_number} from {company_name}",
    body: `Dear {customer_name},

Please find attached your invoice #{invoice_number}.

Total Amount: {total_amount}
Due Date: {due_date}

Thank you for your business!

Best regards,
{company_name}`,
    variables: ["customer_name", "invoice_number", "total_amount", "due_date", "company_name"],
  },
  {
    id: "service_complete",
    name: "Service Complete",
    subject: "Your Vehicle is Ready - {company_name}",
    body: `Dear {customer_name},

Great news! Your vehicle service has been completed.

Vehicle: {vehicle_info}
Services Performed: {services}
Total: {total_amount}

You can pick up your vehicle during our business hours.

Best regards,
{company_name}`,
    variables: ["customer_name", "vehicle_info", "services", "total_amount", "company_name"],
  },
];

export function EmailTemplatesEditor() {
  const [templates, setTemplates] = useState<EmailTemplate[]>(defaultTemplates);
  const [selectedTemplate, setSelectedTemplate] = useState<EmailTemplate>(defaultTemplates[0]);
  const [isSaving, setIsSaving] = useState(false);
  const [showPreview, setShowPreview] = useState(false);

  // Convex queries/mutations
  const savedTemplates = useQuery(api.settings.getEmailTemplates);
  const updateTemplate = useMutation(api.settings.upsertEmailTemplate);

  useEffect(() => {
    if (savedTemplates && savedTemplates.length > 0) {
      setTemplates(savedTemplates as EmailTemplate[]);
      setSelectedTemplate(savedTemplates[0] as EmailTemplate);
    }
  }, [savedTemplates]);

  const handleTemplateChange = (templateId: string) => {
    const template = templates.find((t) => t.id === templateId);
    if (template) {
      setSelectedTemplate(template);
    }
  };

  const handleSubjectChange = (value: string) => {
    setSelectedTemplate((prev) => ({ ...prev, subject: value }));
    setTemplates((prev) =>
      prev.map((t) => (t.id === selectedTemplate.id ? { ...t, subject: value } : t))
    );
  };

  const handleBodyChange = (value: string) => {
    setSelectedTemplate((prev) => ({ ...prev, body: value }));
    setTemplates((prev) =>
      prev.map((t) => (t.id === selectedTemplate.id ? { ...t, body: value } : t))
    );
  };

  const handleSave = async () => {
    setIsSaving(true);
    try {
      await updateTemplate({
        templateId: selectedTemplate.id,
        templateName: selectedTemplate.name,
        subject: selectedTemplate.subject,
        body: selectedTemplate.body,
        variables: selectedTemplate.variables,
      });
      toast.success("Template saved successfully");
    } catch (error) {
      console.error(error);
      toast.error("Failed to save template");
    } finally {
      setIsSaving(false);
    }
  };

  const getPreviewContent = () => {
    let preview = selectedTemplate.body;
    const sampleData: Record<string, string> = {
      user: "John Doe",
      email: "john@example.com",
      password: "NewSecureP@ss123",
      company_name: "MASS Workshop",
      customer_name: "John Doe",
      service_name: "Oil Change",
      booking_date: "January 15, 2026",
      booking_time: "10:00 AM",
      vehicle_info: "Toyota Camry 2022",
      invoice_number: "INV-001",
      total_amount: "$150.00",
      due_date: "January 30, 2026",
      services: "Oil Change, Tire Rotation",
    };

    selectedTemplate.variables.forEach((variable) => {
      preview = preview.replace(new RegExp(`{${variable}}`, "g"), sampleData[variable] || `{${variable}}`);
    });

    return preview;
  };

  return (
    <div className="settings-card">
      <div className="settings-header">
        <span>Email Templates</span>
        <select
          className="bg-white/20 border-none text-white rounded px-3 py-1 text-sm"
          value={selectedTemplate.id}
          onChange={(e) => handleTemplateChange(e.target.value)}
        >
          {templates.map((template) => (
            <option key={template.id} value={template.id} className="text-gray-900">
              {template.name}
            </option>
          ))}
        </select>
      </div>

      <div className="settings-body">
        {/* Variables Reference */}
        <div className="settings-variables mb-4">
          <strong>{selectedTemplate.name} Variables:</strong>
          <div className="mt-1">
            {selectedTemplate.variables.map((variable) => (
              <span key={variable} className="mr-2">
                {`{${variable}}`}
              </span>
            ))}
          </div>
        </div>

        {/* Subject */}
        <div className="settings-field mb-4">
          <label className="settings-label settings-label-required">
            Email Subject
          </label>
          <input
            type="text"
            className="settings-input"
            value={selectedTemplate.subject}
            onChange={(e) => handleSubjectChange(e.target.value)}
          />
        </div>

        {/* Body */}
        <div className="settings-field">
          <label className="settings-label settings-label-required">
            Email Message
          </label>
          {showPreview ? (
            <div className="settings-input settings-textarea whitespace-pre-wrap bg-gray-50 dark:bg-slate-800">
              {getPreviewContent()}
            </div>
          ) : (
            <textarea
              className="settings-input settings-textarea"
              value={selectedTemplate.body}
              onChange={(e) => handleBodyChange(e.target.value)}
            />
          )}
        </div>
      </div>

      <div className="settings-footer">
        <button
          className="settings-btn settings-btn-secondary"
          onClick={() => setShowPreview(!showPreview)}
        >
          <Eye className="w-4 h-4 inline mr-2" />
          {showPreview ? "Edit" : "Preview"}
        </button>
        <button
          className="settings-btn settings-btn-primary"
          onClick={handleSave}
          disabled={isSaving}
        >
          {isSaving ? (
            <Loader2 className="w-4 h-4 animate-spin inline mr-2" />
          ) : null}
          Save
        </button>
      </div>
    </div>
  );
}
